<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2020-09-30T13:34:18 NPT" name="Rest-Assured TestNG Tests" finished-at="2020-09-30T13:34:25 NPT" duration-ms="6497">
    <groups>
    </groups>
    <test started-at="2020-09-30T13:34:18 NPT" name="ListUsers" finished-at="2020-09-30T13:34:25 NPT" duration-ms="6497">
      <class name="services.AfterClassCleanup">
        <test-method is-config="true" signature="cleanup()[pri:0, instance:services.AfterClassCleanup@420745d7]" started-at="2020-09-30T13:34:25 NPT" name="cleanup" finished-at="2020-09-30T13:34:25 NPT" duration-ms="107" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanup -->
      </class> <!-- services.AfterClassCleanup -->
      <class name="services.ListUsers">
        <test-method is-config="true" signature="setEndPoint()[pri:0, instance:services.ListUsers@63034ed1]" started-at="2020-09-30T13:34:18 NPT" name="setEndPoint" finished-at="2020-09-30T13:34:19 NPT" duration-ms="893" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setEndPoint -->
        <test-method signature="testListUserWithValidPageNumber()[pri:0, instance:services.ListUsers@63034ed1]" started-at="2020-09-30T13:34:19 NPT" name="testListUserWithValidPageNumber" finished-at="2020-09-30T13:34:23 NPT" duration-ms="3406" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testListUserWithValidPageNumber -->
        <test-method signature="testListUserWithInvalidPageNumber()[pri:2, instance:services.ListUsers@63034ed1]" started-at="2020-09-30T13:34:23 NPT" name="testListUserWithInvalidPageNumber" finished-at="2020-09-30T13:34:24 NPT" duration-ms="1288" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testListUserWithInvalidPageNumber -->
        <test-method signature="testListUserPageNumberAsInvalidInteger()[pri:3, instance:services.ListUsers@63034ed1]" started-at="2020-09-30T13:34:24 NPT" name="testListUserPageNumberAsInvalidInteger" finished-at="2020-09-30T13:34:25 NPT" duration-ms="641" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testListUserPageNumberAsInvalidInteger -->
      </class> <!-- services.ListUsers -->
      <class name="services.ListUser2">
        <test-method is-config="true" signature="setEndPoint()[pri:0, instance:services.ListUser2@232024b9]" started-at="2020-09-30T13:34:25 NPT" name="setEndPoint" finished-at="2020-09-30T13:34:25 NPT" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setEndPoint -->
        <test-method signature="testListUserWithValidPageNumber()[pri:0, instance:services.ListUser2@232024b9]" started-at="2020-09-30T13:34:25 NPT" name="testListUserWithValidPageNumber" finished-at="2020-09-30T13:34:25 NPT" duration-ms="2" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at services.ListUser2.testListUserWithValidPageNumber(ListUser2.java:11)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testListUserWithValidPageNumber -->
      </class> <!-- services.ListUser2 -->
    </test> <!-- ListUsers -->
  </suite> <!-- Rest-Assured TestNG Tests -->
</testng-results>
